#pragma once

#include <SA2ModLoader.h>
#include <SFML/Network.hpp>
#include <ShellAPI.h>
#include <WTypes.h>
#include <WinSock2.h>
#include <Windows.h>
#include <Winsock2.h>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <map>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

#include "AddressList.h"
#include "AdventurePacketOverloads.h"
#include "BAMS.h"
#include "Common.h"
#include "CommonEnums.h"
#include "Globals.h"
#include "LazyMemory.h"
#include "MainThread.h"
#include "MemoryManagement.h"
#include "MemoryStruct.h"
#include "ModLoaderExtensions.h"
#include "Networking.h"
#include "OnGameState.h"
#include "OnStageChange.h"
#include "PacketBroker.h"
#include "PacketExtensions.h"
#include "PacketHandler.h"
#include "PlayerObject.h"
#include "Program.h"
#include "nop.h"
#include "typedefs.h"
